UserInterfaceWeb/Models/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace UserInterfaceWeb.Models.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private UserManager<IdentityUser> userManager;

        public NavigationMenuViewComponent(UserManager<IdentityUser> userMgr)
        {
            userManager = userMgr;
        }
        public IViewComponentResult Invoke()
        {
            IdentityUser user = userManager.GetUserAsync(HttpContext.User).Result;
            if (user != null)
            {
                ViewBag.Email = user.UserName;
            }
            return View();
        }
    }
}

UserInterfaceWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet"
          asp-href-include="/lib/bootstrap/dist/**/*.min.css"
          asp-href-exclude="**/*-reboot*,**/*-grid*" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/*.css" />
    <link rel="stylesheet" asp-href-include="/css/**" />
    <script asp-src-include="/lib/jquery/jquery.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    <div>
        @RenderBody()
    </div>
    <footer>
        <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
        <script asp-src-include="/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    </footer>
</body>
</html>