ChefUserInterfaceWeb/Models/Components/MealListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DomainServices.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace ChefUserInterfaceWeb.Models.Components
{
    public class MealListViewComponent : ViewComponent
    {
        private IMealDAO mealDAO;

        public MealListViewComponent(IMealDAO mealDAO)
        {
            this.mealDAO = mealDAO;
        }

        public IViewComponentResult Invoke()
        {
            return View(mealDAO.Read().Result);
        }
    }
}

ChefUserInterfaceWeb/Controllers/MealController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ChefUserInterfaceWeb.Models;
using DomainModel;
using DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;


namespace ChefUserInterfaceWeb.Controllers
{
    [Authorize]
    public class MealController : Controller
    {
        private IMealDAO mealDAO;

        public MealController(IMealDAO mealDAO)
        {
            this.mealDAO = mealDAO;
        }

        /**
         * Get Add page
         */
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        /**
         * Post meal
         */
        [HttpPost]
        public async Task<IActionResult> Add(Meal meal, IFormFile image)
        {
            await AddMealHelper.AddMeal(meal, image, mealDAO);
            return View();
        }
    }
}

ChefUserInterfaceWeb/Controllers/MenuController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata.Ecma335;
using System.Threading.Tasks;
using ChefUserInterfaceWeb.Models;
using DomainModel;
using DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ChefUserInterfaceWeb.Controllers
{
    [Authorize]
    public class MenuController : Controller
    {
        private MealCart mealCart;
        private IWeekMenuDAO weekMenuDAO;
        private IChefDAO chefDAO;
        private IMealDAO mealDAO;
        private UserManager<IdentityUser> userManager;

        public MenuController(IWeekMenuDAO weekMenuDAO, IMealDAO mealDAO, IChefDAO chefDAO,
            MealCart mealCart, UserManager<IdentityUser> userMgr)
        {
            this.weekMenuDAO = weekMenuDAO;
            this.mealDAO = mealDAO;
            this.chefDAO = chefDAO;
            this.mealCart = mealCart;
            userManager = userMgr;
        }

        public async Task<IActionResult> Index()
        {
            List<WeekMenu> weekMenus = await weekMenuDAO.Read();
            return View(weekMenus);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(WeekMenu weekMenu)
        {
            IdentityUser user = await userManager.GetUserAsync(HttpContext.User);

            if (await AddMenuHelper.AddMenu(weekMenu, mealCart, weekMenuDAO, user, chefDAO))
            {
                mealCart.Clear();
                return Redirect("Index");
            } else
            {
                mealCart.Clear();
                ModelState.AddModelError("NotAllDiets", "Er moet minimaal voor ieder dieet een maaltijd zitten in een menu");
                return View();
            }
        }

        [HttpPost]
        public async Task<IActionResult> AddMealToMenu(Meal meal)
        {
            Meal dbMeal = await mealDAO.ReadById(meal.Id);
            mealCart.AddItem(dbMeal, 1);
            return Redirect("Add");
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMealFromMenu(Meal meal)
        {
            Meal dbMeal = await mealDAO.ReadById(meal.Id);
            mealCart.RemoveLine(dbMeal);
            return Redirect("Add");
        }
    }
}

ChefUserInterfaceWeb/Views/Menu/Add.cshtml
@using DomainModel
@model DomainModel.WeekMenu

    <div class="container-custom">
        <div class="row">
            <div class="col-md-8">
                <div class="card card-margin-top box-shadow">
                    <h2 class="card-header">Menu aanmaken</h2>
                    <div class="card-padding">
                        @await Component.InvokeAsync("MealList")
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card card-margin-top box-shadow">
                    <h2 class="card-header">Menu</h2>
                    <div class="card-padding">
                        @if (!ViewData.ModelState.IsValid)
                        {
                            <div class="alert alert-danger" role="alert" asp-validation-summary="All"></div>
                        }
                        <form asp-action="Add" method="post" class="form" role="form">
                            <div class="row margin-bottom">
                                <div class="col-12">
                                    <label>Datum vanaf</label>
                                    <input class="form-control" name="BeginDate" type="date"
                                           required autofocus />
                                </div>
                                <div class="col-12">
                                    <label>Datum tot</label>
                                    <input class="form-control" name="EndDate" type="date"
                                           required />
                                </div>
                            </div>
                            <table class="table table-striped table-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Naam</th>
                                        <th scope="col"></th>
                                    </tr>
                                </thead>
                                <tbody class="meal-in-menu">
                                </tbody>
                            </table>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">
                                Aanmaken
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script asp-src-include="/js/menu.js"></script>

ChefUserInterfaceWeb/Views/Menu/Index.cshtml
@using DomainModel
@model IList<DomainModel.WeekMenu>

<div class="container-custom">
    <h1 class="header-text">Menus</h1>
    <div class="row">
        <div class="col-md-3">
            <div class="card card-margin-top box-shadow">
                <h2 class="card-header">Menu aanmaken</h2>
                <div class="card-padding">
                    <form action="#" method="post" class="form" role="form">
                        <a class="btn btn-lg btn-primary btn-block" asp-controller="Menu" asp-action="Add">
                            Plaatsen
                        </a>
                    </form>
                </div>
            </div>
            <div class="card card-margin-top box-shadow">
                <h2 class="card-header">Maaltijd aanmaken</h2>
                <div class="card-padding">
                    <form action="#" method="post" class="form" role="form">
                        <a class="btn btn-lg btn-primary btn-block" asp-controller="Meal" asp-action="Add">
                            Plaatsen
                        </a>
                    </form>
                </div>
            </div>
            <div class="card card-margin-top box-shadow">
                <h2 class="card-header">Chef aanmaken</h2>
                <div class="card-padding">
                    <form action="#" method="post" class="form" role="form">
                        <a class="btn btn-lg btn-primary btn-block" asp-controller="Account" asp-action="Add">
                            Aanmaken
                        </a>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            @if (@Model.Count > 0)
            {
                <table class="table table-striped card-margin-top box-shadow">
                    <thead>
                        <tr class="bg-orange text-white">
                            <th scope="col">
                                <h3>Week</h3>
                            </th>
                            <th scope="col">
                                <h3>Aantal gerechten</h3>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var meal in Model)
                        {
                            <tr>
                                <td>@meal.BeginDate.ToString("d MMMM yyyy") t/m @meal.EndDate.ToString("d MMMM yyyy")</td>

                                <td>
                                    @foreach (Meal mealInWeekMenu in @meal.Meals)
                                    {
                                    <span class="badge badge-orange">@mealInWeekMenu.Name</span>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <div class="text-center margin-top-big"><h4>Er zijn nog geen menu's geplaatst</h4></div>
            }
        </div>
    </div>
</div>